# coding: utf-8

"""
    API's OpenData do Open Banking Brasil

    As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import products-services_1_0_0_yml
from products-services_1_0_0_yml.models.credit_card_indentification import CreditCardIndentification  # noqa: E501
from products-services_1_0_0_yml.rest import ApiException


class TestCreditCardIndentification(unittest.TestCase):
    """CreditCardIndentification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreditCardIndentification(self):
        """Test CreditCardIndentification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = products-services_1_0_0_yml.models.credit_card_indentification.CreditCardIndentification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
