# coding: utf-8

"""
    Participantes Open Finance Brasil

    Informações sobre os participantes do Open Finance Brasil que estão registrados no Diretório.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthorityAuthorisationDomain(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authorisation_domain_name': 'str',
        'authority_id': 'str',
        'authority_authorisation_domain_id': 'str',
        'status': 'str'
    }

    attribute_map = {
        'authorisation_domain_name': 'AuthorisationDomainName',
        'authority_id': 'AuthorityId',
        'authority_authorisation_domain_id': 'AuthorityAuthorisationDomainId',
        'status': 'Status'
    }

    def __init__(self, authorisation_domain_name=None, authority_id=None, authority_authorisation_domain_id=None, status='Active'):  # noqa: E501
        """AuthorityAuthorisationDomain - a model defined in Swagger"""  # noqa: E501
        self._authorisation_domain_name = None
        self._authority_id = None
        self._authority_authorisation_domain_id = None
        self._status = None
        self.discriminator = None
        if authorisation_domain_name is not None:
            self.authorisation_domain_name = authorisation_domain_name
        if authority_id is not None:
            self.authority_id = authority_id
        if authority_authorisation_domain_id is not None:
            self.authority_authorisation_domain_id = authority_authorisation_domain_id
        if status is not None:
            self.status = status

    @property
    def authorisation_domain_name(self):
        """Gets the authorisation_domain_name of this AuthorityAuthorisationDomain.  # noqa: E501

        The authorisation domain name  # noqa: E501

        :return: The authorisation_domain_name of this AuthorityAuthorisationDomain.  # noqa: E501
        :rtype: str
        """
        return self._authorisation_domain_name

    @authorisation_domain_name.setter
    def authorisation_domain_name(self, authorisation_domain_name):
        """Sets the authorisation_domain_name of this AuthorityAuthorisationDomain.

        The authorisation domain name  # noqa: E501

        :param authorisation_domain_name: The authorisation_domain_name of this AuthorityAuthorisationDomain.  # noqa: E501
        :type: str
        """

        self._authorisation_domain_name = authorisation_domain_name

    @property
    def authority_id(self):
        """Gets the authority_id of this AuthorityAuthorisationDomain.  # noqa: E501

        The GUID of the Authority  # noqa: E501

        :return: The authority_id of this AuthorityAuthorisationDomain.  # noqa: E501
        :rtype: str
        """
        return self._authority_id

    @authority_id.setter
    def authority_id(self, authority_id):
        """Sets the authority_id of this AuthorityAuthorisationDomain.

        The GUID of the Authority  # noqa: E501

        :param authority_id: The authority_id of this AuthorityAuthorisationDomain.  # noqa: E501
        :type: str
        """

        self._authority_id = authority_id

    @property
    def authority_authorisation_domain_id(self):
        """Gets the authority_authorisation_domain_id of this AuthorityAuthorisationDomain.  # noqa: E501

        The GUID of the Authority-Domain mapping  # noqa: E501

        :return: The authority_authorisation_domain_id of this AuthorityAuthorisationDomain.  # noqa: E501
        :rtype: str
        """
        return self._authority_authorisation_domain_id

    @authority_authorisation_domain_id.setter
    def authority_authorisation_domain_id(self, authority_authorisation_domain_id):
        """Sets the authority_authorisation_domain_id of this AuthorityAuthorisationDomain.

        The GUID of the Authority-Domain mapping  # noqa: E501

        :param authority_authorisation_domain_id: The authority_authorisation_domain_id of this AuthorityAuthorisationDomain.  # noqa: E501
        :type: str
        """

        self._authority_authorisation_domain_id = authority_authorisation_domain_id

    @property
    def status(self):
        """Gets the status of this AuthorityAuthorisationDomain.  # noqa: E501

        Is this user Active or Inactive  # noqa: E501

        :return: The status of this AuthorityAuthorisationDomain.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AuthorityAuthorisationDomain.

        Is this user Active or Inactive  # noqa: E501

        :param status: The status of this AuthorityAuthorisationDomain.  # noqa: E501
        :type: str
        """
        allowed_values = ["Active", "Inactive"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorityAuthorisationDomain, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorityAuthorisationDomain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
