# coding: utf-8

"""
    APIs OpenData do Open Banking Brasil

    As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import common_1_0_0_yml
from common_1_0_0_yml.models.status_inner import StatusInner  # noqa: E501
from common_1_0_0_yml.rest import ApiException


class TestStatusInner(unittest.TestCase):
    """StatusInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusInner(self):
        """Test StatusInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = common_1_0_0_yml.models.status_inner.StatusInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
