# coding: utf-8

"""
    API Pension - Open Finance Brasil

    API de Previdência do Open Finance Brasil – Fase 4. API que retorna informações de Previdência.   # noqa: E501

    OpenAPI spec version: 1.0.0-rc3.0
    Contact: gt-interfaces@openbankingbr.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SurvivalPensionMinimumRequirements(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contract_type': 'str',
        'participant_qualified': 'bool',
        'contracting_min_requirement': 'str'
    }

    attribute_map = {
        'contract_type': 'contractType',
        'participant_qualified': 'participantQualified',
        'contracting_min_requirement': 'contractingMinRequirement'
    }

    def __init__(self, contract_type=None, participant_qualified=None, contracting_min_requirement=None):  # noqa: E501
        """SurvivalPensionMinimumRequirements - a model defined in Swagger"""  # noqa: E501
        self._contract_type = None
        self._participant_qualified = None
        self._contracting_min_requirement = None
        self.discriminator = None
        self.contract_type = contract_type
        if participant_qualified is not None:
            self.participant_qualified = participant_qualified
        self.contracting_min_requirement = contracting_min_requirement

    @property
    def contract_type(self):
        """Gets the contract_type of this SurvivalPensionMinimumRequirements.  # noqa: E501

        O tipo de serviço contratado. A considerar os domínios abaixo: 1. Coletivo Averbado; 2. Coletivo instituído; 3. Individual. 4. NA   # noqa: E501

        :return: The contract_type of this SurvivalPensionMinimumRequirements.  # noqa: E501
        :rtype: str
        """
        return self._contract_type

    @contract_type.setter
    def contract_type(self, contract_type):
        """Sets the contract_type of this SurvivalPensionMinimumRequirements.

        O tipo de serviço contratado. A considerar os domínios abaixo: 1. Coletivo Averbado; 2. Coletivo instituído; 3. Individual. 4. NA   # noqa: E501

        :param contract_type: The contract_type of this SurvivalPensionMinimumRequirements.  # noqa: E501
        :type: str
        """
        if contract_type is None:
            raise ValueError("Invalid value for `contract_type`, must not be `None`")  # noqa: E501
        allowed_values = ["COLETIVO_AVERBADO", "COLETIVO_INSTITUIDO", "INDIVIDUAL", "NA"]  # noqa: E501
        if contract_type not in allowed_values:
            raise ValueError(
                "Invalid value for `contract_type` ({0}), must be one of {1}"  # noqa: E501
                .format(contract_type, allowed_values)
            )

        self._contract_type = contract_type

    @property
    def participant_qualified(self):
        """Gets the participant_qualified of this SurvivalPensionMinimumRequirements.  # noqa: E501

        Indicação se o plano é destinado para participante qualificado. A considerar os domínios abaixo: 1. true 2. false   # noqa: E501

        :return: The participant_qualified of this SurvivalPensionMinimumRequirements.  # noqa: E501
        :rtype: bool
        """
        return self._participant_qualified

    @participant_qualified.setter
    def participant_qualified(self, participant_qualified):
        """Sets the participant_qualified of this SurvivalPensionMinimumRequirements.

        Indicação se o plano é destinado para participante qualificado. A considerar os domínios abaixo: 1. true 2. false   # noqa: E501

        :param participant_qualified: The participant_qualified of this SurvivalPensionMinimumRequirements.  # noqa: E501
        :type: bool
        """

        self._participant_qualified = participant_qualified

    @property
    def contracting_min_requirement(self):
        """Gets the contracting_min_requirement of this SurvivalPensionMinimumRequirements.  # noqa: E501

        Campo aberto (possibilidade de incluir URL)  # noqa: E501

        :return: The contracting_min_requirement of this SurvivalPensionMinimumRequirements.  # noqa: E501
        :rtype: str
        """
        return self._contracting_min_requirement

    @contracting_min_requirement.setter
    def contracting_min_requirement(self, contracting_min_requirement):
        """Sets the contracting_min_requirement of this SurvivalPensionMinimumRequirements.

        Campo aberto (possibilidade de incluir URL)  # noqa: E501

        :param contracting_min_requirement: The contracting_min_requirement of this SurvivalPensionMinimumRequirements.  # noqa: E501
        :type: str
        """
        if contracting_min_requirement is None:
            raise ValueError("Invalid value for `contracting_min_requirement`, must not be `None`")  # noqa: E501

        self._contracting_min_requirement = contracting_min_requirement

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SurvivalPensionMinimumRequirements, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SurvivalPensionMinimumRequirements):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
