# coding: utf-8

"""
    API Pension - Open Finance Brasil

    API de Previdência do Open Finance Brasil – Fase 4. API que retorna informações de Previdência.   # noqa: E501

    OpenAPI spec version: 1.0.0-rc1.0
    Contact: gt-interfaces@openbankingbr.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pension_1_0_0-rc1_0_yml
from pension_1_0_0-rc1_0_yml.models.survival_pension_costs import SurvivalPensionCosts  # noqa: E501
from pension_1_0_0-rc1_0_yml.rest import ApiException


class TestSurvivalPensionCosts(unittest.TestCase):
    """SurvivalPensionCosts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSurvivalPensionCosts(self):
        """Test SurvivalPensionCosts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pension_1_0_0-rc1_0_yml.models.survival_pension_costs.SurvivalPensionCosts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
