# coding: utf-8

"""
    APIs Admin do Open Banking Brasil

    As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import admin_1_0_0-rc5_2_yml
from admin_1_0_0-rc5_2_yml.models.average_metrics import AverageMetrics  # noqa: E501
from admin_1_0_0-rc5_2_yml.rest import ApiException


class TestAverageMetrics(unittest.TestCase):
    """AverageMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAverageMetrics(self):
        """Test AverageMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = admin_1_0_0-rc5_2_yml.models.average_metrics.AverageMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
