# coding: utf-8

"""
    API's OpenData do Open Banking Brasil

    As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import products-services_1_0_0-rc5_2_yml
from products-services_1_0_0-rc5_2_yml.models.price import Price  # noqa: E501
from products-services_1_0_0-rc5_2_yml.rest import ApiException


class TestPrice(unittest.TestCase):
    """Price unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrice(self):
        """Test Price"""
        # FIXME: construct object with mandatory attributes with example values
        # model = products-services_1_0_0-rc5_2_yml.models.price.Price()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
