# coding: utf-8

"""
    API's OpenData do Open Banking Brasil

    As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PersonalAccountsResponseDataBrandFees(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'priority_service': 'PersonalAccountsPriorityServices',
        'other_service': 'PersonalAccountsOtherServices'
    }

    attribute_map = {
        'priority_service': 'priorityService',
        'other_service': 'otherService'
    }

    def __init__(self, priority_service=None, other_service=None):  # noqa: E501
        """PersonalAccountsResponseDataBrandFees - a model defined in Swagger"""  # noqa: E501
        self._priority_service = None
        self._other_service = None
        self.discriminator = None
        if priority_service is not None:
            self.priority_service = priority_service
        if other_service is not None:
            self.other_service = other_service

    @property
    def priority_service(self):
        """Gets the priority_service of this PersonalAccountsResponseDataBrandFees.  # noqa: E501


        :return: The priority_service of this PersonalAccountsResponseDataBrandFees.  # noqa: E501
        :rtype: PersonalAccountsPriorityServices
        """
        return self._priority_service

    @priority_service.setter
    def priority_service(self, priority_service):
        """Sets the priority_service of this PersonalAccountsResponseDataBrandFees.


        :param priority_service: The priority_service of this PersonalAccountsResponseDataBrandFees.  # noqa: E501
        :type: PersonalAccountsPriorityServices
        """

        self._priority_service = priority_service

    @property
    def other_service(self):
        """Gets the other_service of this PersonalAccountsResponseDataBrandFees.  # noqa: E501


        :return: The other_service of this PersonalAccountsResponseDataBrandFees.  # noqa: E501
        :rtype: PersonalAccountsOtherServices
        """
        return self._other_service

    @other_service.setter
    def other_service(self, other_service):
        """Sets the other_service of this PersonalAccountsResponseDataBrandFees.


        :param other_service: The other_service of this PersonalAccountsResponseDataBrandFees.  # noqa: E501
        :type: PersonalAccountsOtherServices
        """

        self._other_service = other_service

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PersonalAccountsResponseDataBrandFees, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonalAccountsResponseDataBrandFees):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
