# coding: utf-8

"""
    API OpenData Credit Cards do Open Finance Brasil

    A API descrita neste documento é referente as API Credit Cards da fase OpenData do Open Finance Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-beta.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opendata-creditcards_1_0_0-beta_2_yml
from opendata-creditcards_1_0_0-beta_2_yml.models.required_warranty import RequiredWarranty  # noqa: E501
from opendata-creditcards_1_0_0-beta_2_yml.rest import ApiException


class TestRequiredWarranty(unittest.TestCase):
    """RequiredWarranty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredWarranty(self):
        """Test RequiredWarranty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opendata-creditcards_1_0_0-beta_2_yml.models.required_warranty.RequiredWarranty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
