# coding: utf-8

"""
    APIs OpenData do Open Banking Brasil

    As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channels_2_0_0_yml
from channels_2_0_0_yml.models.availability import Availability  # noqa: E501
from channels_2_0_0_yml.rest import ApiException


class TestAvailability(unittest.TestCase):
    """Availability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailability(self):
        """Test Availability"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channels_2_0_0_yml.models.availability.Availability()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
