# coding: utf-8

"""
    API OpenData Loans do Open Finance Brasil

    A API descrita neste documento é referente as API Loans da fase OpenData do Open Finance Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-beta.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opendata-loans_1_0_0-beta_1_yml
from opendata-loans_1_0_0-beta_1_yml.models.loan_fees import LoanFees  # noqa: E501
from opendata-loans_1_0_0-beta_1_yml.rest import ApiException


class TestLoanFees(unittest.TestCase):
    """LoanFees unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoanFees(self):
        """Test LoanFees"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opendata-loans_1_0_0-beta_1_yml.models.loan_fees.LoanFees()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
