# coding: utf-8

# flake8: noqa

"""
    API Webhook - Open Finance Brasil

    API de Webhook é responsável por notificar eventos definidos em cada uma das APIs que possuem a funcionalidade no Open Finance Brasil.  <u>Endpoints que possuem a funcionalidade de Webhook</u> <br/>  Na versão atual, temos os seguintes endpoints:   API Payments v2:   - POST /pix/payments   - POST /consents  # Orientações <u>Todos os endpoints nessa API utilizam-se de mTLS para autenticação, não possuem scopes e permissions específicos de segurança. Toda a segurança é feita via certificado(mTLS – BRCAC).</u>  Dado que as URLs do ecossistema são formadas com a configuração abaixo:   \\<host> / \\<string> / \\<api> / \\<versão> / \\<recurso>  <u>Para a utilização desse recurso é necessário que:</u> - Iniciadoras de pagamentos e/ou Receptora de dados: Precisam cadastrar a sua URI base (\\<host>) no diretório de participantes no campo `<CAMPO_A_DEFINIR>`, - Detentoras de contas e/ou Transmissora de dados: Precisam construir a URI de notificação da seguinte forma:  <u>Exemplo de URI do consentimento:</u> <br/> <br/> <img src=\"./img/image001.png\" alt=\"Image Webhook\"/> <br/> <br/>  <u>Exemplo de URI do pagamento:</u> <br/> <br/> <img src=\"./img/image002.png\" alt=\"Image Webhook\"/>   # noqa: E501

    OpenAPI spec version: 1.0.0-beta1
    Contact: gt-interfaces@openbankingbr.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from webhook_1_0_0-beta1_yml.api.consent_notification_api import ConsentNotificationApi
from webhook_1_0_0-beta1_yml.api.pix_payment_notification_api import PixPaymentNotificationApi
# import ApiClient
from webhook_1_0_0-beta1_yml.api_client import ApiClient
from webhook_1_0_0-beta1_yml.configuration import Configuration
# import models into sdk package
from webhook_1_0_0-beta1_yml.models.request_body_webhook import RequestBodyWebhook
from webhook_1_0_0-beta1_yml.models.request_body_webhook_data import RequestBodyWebhookData
from webhook_1_0_0-beta1_yml.models.x_webhook_interaction_id import XWebhookInteractionId
