# coding: utf-8

"""
    API OpenData Accounts do Open Finance Brasil

    A API descrita neste documento é referente as API Accounts da fase OpenData do Open Finance Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-beta.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opendata-accounts_1_0_0-beta_1_yml
from opendata-accounts_1_0_0-beta_1_yml.models.accounts_income_rate import AccountsIncomeRate  # noqa: E501
from opendata-accounts_1_0_0-beta_1_yml.rest import ApiException


class TestAccountsIncomeRate(unittest.TestCase):
    """AccountsIncomeRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsIncomeRate(self):
        """Test AccountsIncomeRate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opendata-accounts_1_0_0-beta_1_yml.models.accounts_income_rate.AccountsIncomeRate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
