# coding: utf-8

"""
    Participantes Open Finance Brasil

    Informações sobre os participantes do Open Finance Brasil que estão registrados no Diretório.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import participants_1_0_0_yml
from participants_1_0_0_yml.models.authorisation_domains import AuthorisationDomains  # noqa: E501
from participants_1_0_0_yml.rest import ApiException


class TestAuthorisationDomains(unittest.TestCase):
    """AuthorisationDomains unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorisationDomains(self):
        """Test AuthorisationDomains"""
        # FIXME: construct object with mandatory attributes with example values
        # model = participants_1_0_0_yml.models.authorisation_domains.AuthorisationDomains()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
