# coding: utf-8

"""
    API OpenData Unarranged Account Overdraft do Open Finance Brasil​

    A API descrita neste documento é referente as API Unarranged Account Overdraft da fase OpenData do Open Finance Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-beta.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BusinessUnarrangedAccountOverdraftData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'participant': 'Participant',
        'fees': 'BusinessUnarrangedAccountOverdraftFee',
        'interest_rates': 'list[UnarrangedAccountOverdraftRate]',
        'terms_conditions': 'str'
    }

    attribute_map = {
        'participant': 'participant',
        'fees': 'fees',
        'interest_rates': 'interestRates',
        'terms_conditions': 'termsConditions'
    }

    def __init__(self, participant=None, fees=None, interest_rates=None, terms_conditions=None):  # noqa: E501
        """BusinessUnarrangedAccountOverdraftData - a model defined in Swagger"""  # noqa: E501
        self._participant = None
        self._fees = None
        self._interest_rates = None
        self._terms_conditions = None
        self.discriminator = None
        if participant is not None:
            self.participant = participant
        self.fees = fees
        if interest_rates is not None:
            self.interest_rates = interest_rates
        self.terms_conditions = terms_conditions

    @property
    def participant(self):
        """Gets the participant of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501


        :return: The participant of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :rtype: Participant
        """
        return self._participant

    @participant.setter
    def participant(self, participant):
        """Sets the participant of this BusinessUnarrangedAccountOverdraftData.


        :param participant: The participant of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :type: Participant
        """

        self._participant = participant

    @property
    def fees(self):
        """Gets the fees of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501


        :return: The fees of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :rtype: BusinessUnarrangedAccountOverdraftFee
        """
        return self._fees

    @fees.setter
    def fees(self, fees):
        """Sets the fees of this BusinessUnarrangedAccountOverdraftData.


        :param fees: The fees of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :type: BusinessUnarrangedAccountOverdraftFee
        """
        if fees is None:
            raise ValueError("Invalid value for `fees`, must not be `None`")  # noqa: E501

        self._fees = fees

    @property
    def interest_rates(self):
        """Gets the interest_rates of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501

        Lista que traz o conjunto de informações necessárias para demonstrar a distribuição de frequências das taxas de juros remuneratórios da Modalidade de crédito  # noqa: E501

        :return: The interest_rates of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :rtype: list[UnarrangedAccountOverdraftRate]
        """
        return self._interest_rates

    @interest_rates.setter
    def interest_rates(self, interest_rates):
        """Sets the interest_rates of this BusinessUnarrangedAccountOverdraftData.

        Lista que traz o conjunto de informações necessárias para demonstrar a distribuição de frequências das taxas de juros remuneratórios da Modalidade de crédito  # noqa: E501

        :param interest_rates: The interest_rates of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :type: list[UnarrangedAccountOverdraftRate]
        """

        self._interest_rates = interest_rates

    @property
    def terms_conditions(self):
        """Gets the terms_conditions of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501

        Campo aberto para informar as condições contratuais relativas à Modalidade de Adiantamento a depositante para pessoa natural. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Endereço eletrônico de acesso ao canal.  # noqa: E501

        :return: The terms_conditions of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :rtype: str
        """
        return self._terms_conditions

    @terms_conditions.setter
    def terms_conditions(self, terms_conditions):
        """Sets the terms_conditions of this BusinessUnarrangedAccountOverdraftData.

        Campo aberto para informar as condições contratuais relativas à Modalidade de Adiantamento a depositante para pessoa natural. Pode ser informada a URL referente ao endereço onde constam as condições informadas. Endereço eletrônico de acesso ao canal.  # noqa: E501

        :param terms_conditions: The terms_conditions of this BusinessUnarrangedAccountOverdraftData.  # noqa: E501
        :type: str
        """
        if terms_conditions is None:
            raise ValueError("Invalid value for `terms_conditions`, must not be `None`")  # noqa: E501

        self._terms_conditions = terms_conditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BusinessUnarrangedAccountOverdraftData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BusinessUnarrangedAccountOverdraftData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
