# coding: utf-8

"""
    API Enrollments for Payment Initiation - Open Finance Brasil

    API de Dispositivo Vínculado para suportar Iniciação de Pagamentos na Jornada Sem Redirecionamento do Open Finance Brasil.   # noqa: E501

    OpenAPI spec version: 1.0.0-rc.1
    Contact: squad-jornada@openfinancebrasil.org.br
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import enrollments_1_0_0-rc_1_yml
from enrollments_1_0_0-rc_1_yml.models.model422_response_error_fido_registration_options import Model422ResponseErrorFidoRegistrationOptions  # noqa: E501
from enrollments_1_0_0-rc_1_yml.rest import ApiException


class TestModel422ResponseErrorFidoRegistrationOptions(unittest.TestCase):
    """Model422ResponseErrorFidoRegistrationOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel422ResponseErrorFidoRegistrationOptions(self):
        """Test Model422ResponseErrorFidoRegistrationOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = enrollments_1_0_0-rc_1_yml.models.model422_response_error_fido_registration_options.Model422ResponseErrorFidoRegistrationOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
